## Section A

In [17]:
list = [20, 40, 60, 80, 100]
list.append(100)
list.extend([140,160])
list.insert(1,20)
list.remove(100)
popped_value = list.pop()
print(f"resulting list: {list}")
print(f"Index of 60: {list.index(60)}")
print(f"Count of 40: {list.count(40)}")
list.clear()

resulting list: [20, 20, 40, 60, 80, 100, 140]
Index of 60: 3
Count of 80: 1


In [17]:
list = [20, 40, 60, 80, 100]
list.append(100)
list.extend([140,160])
list.insert(1,20)
list.remove(100)
popped_value = list.pop()
print(f"resulting list: {list}")
print(f"Index of 60: {list.index(60)}")
print(f"Count of 40: {list.count(40)}")
list.clear()

resulting list: [20, 20, 40, 60, 80, 100, 140]
Index of 60: 3
Count of 80: 1


In [18]:
students = ("adarsh","anil","prajwal")
students[1] = "prem"

TypeError: 'tuple' object does not support item assignment

In [19]:
set_of_values = {10, 20, 20, 30, 40, 40, 50,60,60}
print(set_of_values)

{50, 20, 40, 10, 60, 30}


explaination:
sets automatically remove any duplicates and gives output in unstructured way it does not have any defined set

In [20]:
dict={'name':'lingaraj','age': 22,'city': 'kalaburgi'}
dict['age'] = 23
dict['eamil'] = 'lingarajkalashetti@gmail.com'
print(dict)

{'name': 'lingaraj', 'age': 23, 'city': 'kalaburgi', 'eamil': 'lingarajkalashetti@gmail.com'}


In [21]:
age = int(input("Enter the valid age: "))
if age >= 18:
    print("candidate is eligible for voting: ")
else:
    print("Your not eligible! ")

Enter the valid age:  20


candidate is eligible for voting: 


In [23]:
marks = int(input("Enter the obtained marks: "))
if marks >= 90:
    print("Grade: A ")
elif marks >= 75:
    print("Grade: B ")
elif marks >= 50:
    print("Grade: c")
else:
    print("Fail")

Enter the obtained marks:  40


Fail


In [25]:
num = int(input("Eneter the number: "))
if num >= 0:
    print("positive ")
    if num % 2 == 0:
        print("even")
else:
    print("non-zero or negative ")

Eneter the number:  -20


non-zero or negative 


## Section B

8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10


In [32]:
import numpy as np
scalar = np.array(5)
array_1d = np.arange(1,6)
array_2d = np.arange(10, 70, 10).reshape(2,3)
print(array_1d)
print(array_2d)

[1 2 3 4 5]
[[10 20 30]
 [40 50 60]]


9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [37]:
random_array = np.random.randint(4, 80, size=(4,4))
random_array

array([[19,  6, 66, 15],
       [66,  8, 10, 53],
       [46, 29, 71,  6],
       [23, 44, 63, 26]], dtype=int32)

10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [41]:
import pandas as pd
array_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
numpy_2d = pd.DataFrame(array_2d,columns=['A','B','c'])
print(numpy_2d)

   A  B  c
0  1  2  3
1  4  5  6
2  7  8  9


## Section C

11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows


In [59]:
import pandas as pd 
import numpy as np
import warnings
warnings.filterwarnings('ignore')

data ={
       'name':['raj','veer','rajesh','smithi','navven','veena','jai','hrithik','virat','priya'],
       'age':[24,25,27,28,32,26,30,31,26,33],
       'city':['bangalore','mumbai','delhi','kolkata','pune','ranchi','kochi','hydrabad','bidar','bengal'],
       'salary':[25000,22000,27000,32000,np.nan,29000,38000,40000,26000,50000]
}
df = pd.DataFrame(data)
print(df.info())
print(df.describe())

name_city = df[['name','city']]
drop = df.drop(columns=['city'])
df['salary'] = df['salary'].fillna(df['salary'].mean())
df = df.drop_duplicates()
print("\nFinal clean DataFrame")
print(df)


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   name    10 non-null     object 
 1   age     10 non-null     int64  
 2   city    10 non-null     object 
 3   salary  9 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes
None
             age        salary
count  10.000000      9.000000
mean   28.200000  32111.111111
std     3.119829   8964.435906
min    24.000000  22000.000000
25%    26.000000  26000.000000
50%    27.500000  29000.000000
75%    30.750000  38000.000000
max    33.000000  50000.000000

Final clean DataFrame
      name  age       city        salary
0      raj   24  bangalore  25000.000000
1     veer   25     mumbai  22000.000000
2   rajesh   27      delhi  27000.000000
3   smithi   28    kolkata  32000.000000
4   navven   32       pune  32111.111111
5    veena   26     ranchi  29000.000000
6      jai   30 